[package]
name = "_"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.87"
xxhash-rust = {version="0.8.7",features=["xxh3"]}

[profile.release]
lto = true

