[package]
name = "_"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.71"
base64 = "0.21.2"
vbyte = "0.1.0"
wasm-bindgen = "0.2.87"

[profile.release]
opt-level = 's'
lto = true
