/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_binmap_free(a: number): void;
export function binmap_new(): number;
export function binmap_size(a: number): number;
export function binmap_delete(a: number, b: number, c: number): number;
export function binmap_set(a: number, b: number, c: number, d: number): void;
export function binmap_get(a: number, b: number, c: number): number;
export function z85E(a: number, b: number, c: number): void;
export function z85D(a: number, b: number, c: number): void;
export function b64E(a: number, b: number, c: number): void;
export function b64D(a: number, b: number, c: number): void;
export function __wbg_binset_free(a: number): void;
export function binset_clear(a: number, b: number): void;
export function binset_add(a: number, b: number, c: number): number;
export function binset_has(a: number, b: number, c: number): number;
export function binset_delete(a: number, b: number, c: number): number;
export function u64Bin(a: number, b: number): void;
export function u64B64(a: number, b: number): void;
export function vbyteE(a: number, b: number, c: number): void;
export function vbyteD(a: number, b: number, c: number): void;
export function b64VbyteE(a: number, b: number, c: number): void;
export function b64VbyteD(a: number, b: number, c: number): void;
export function binset_size(a: number): number;
export function binset_new(): number;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
